[build]
  command = "yarn build"
  functions = "lambda/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/post"
  to = "/.netlify/functions/post"
  status = 200